const Images = {
  like: require('../assets/bkg_img/like.png'),
  vpnlogo: require('../assets/bkg_img/vpnlogo.png'),
  vpnlogo1: require('../assets/bkg_img/vpnlogo1.png'),
  vpnlogogray: require('../assets/bkg_img/vpnlogogray.png'),
  bgimage: require('../assets/bkg_img/bgimage.png'),
  gobackicon: require('../assets/bkg_img/gobackicon.png'),
  searchiconblue: require('../assets/bkg_img/searchiconblue.png'),
  usflag: require('../assets/bkg_img/usflag.png'),
  tongaflag: require('../assets/bkg_img/tongaflag.png'),
  thailandflag: require('../assets/bkg_img/thailandflag.png'),
  turkeryflag: require('../assets/bkg_img/turkeyflag.png'),
  ugandaflag: require('../assets/bkg_img/ugandaflag.png'),
  ukraineflag: require('../assets/bkg_img/ukraineflag.png'),
  ukflag: require('../assets/bkg_img/ukflag.png'),
  netherlandflag: require('../assets/bkg_img/netherlandflag.png'),
  singaporeflag: require('../assets/bkg_img/singaporeflag.png'),
  indiaflag: require('../assets/bkg_img/indiaflag.png'),
  californiaflag: require('../assets/bkg_img/californiaflag.png'),
  germanyflag: require('../assets/bkg_img/germanyflag.png'),
  loadingbackground: require('../assets/bkg_img/loadingbackground.png'),
  home: require('../assets/bkg_img/home.png'),
  countries: require('../assets/bkg_img/countries.png'),
  notification: require('../assets/bkg_img/notification.png'),
  subscriptionicon: require('../assets/bkg_img/subscriptionicon.png'),
  drawericon: require('../assets/bkg_img/drawericon.png'),
  arrowrighticon: require('../assets/bkg_img/arrowrighticon.png'),
  buttonring: require('../assets/bkg_img/buttonring.png'),
  buttonpowericon: require('../assets/bkg_img/buttonpowericon.png'),
  buttondisconnectedicon: require('../assets/bkg_img/buttondisconnectedicon.png'),
  connectingicon: require('../assets/bkg_img/connectingicon.png'),
  dataicon: require('../assets/bkg_img/dataicon.png'),
  timericon: require('../assets/bkg_img/timericon.png'),
  crossicon: require('../assets/bkg_img/crossicon.png'),

};

export default Images;